# Generated by Django 6.0.2 on 2026-02-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='patients.patient')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='specialists.specialist')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['specialist', 'start_time'], name='bookings_bo_special_46e4ef_idx')],
            },
        ),
    ]
